const language = {
  en: {
    profile: "Profile",
    yourPhoto: "Your photo",
    uploadPhoto: "Upload photo",
    name: "Name",
    enterName: "Enter name",
    email: "Email",
    enterEmail: "Enter email",
    password: "Password",
    enterPassword: "Enter password",
    changePassword: "Change password",
    updateProfile: "Update profile",
    listChildAccount: "List Child Account",
    show: "Show",
    rows: "Rows",
    add: "Add",
    delete: "Delete",
    status: "Status",
    originalQuota: "Original Quota",
    remainQuota: "Remain Quota",
    action: "Action",
    company: "Company",
    address: "Address",
    currentTotalQuota: "Current Total Quota",
    currentPlan: "Current Plan",
    changePlan: "Change Plan",
    buyMoreQuota: "Buy more Quota",
    businessOne: "Business1",
    token: "Token",
    active: "Active",
    deactive: "Deactive",
    changeYourPassword: "Change your password",
    pleaseEnterYourPassword: "Please enter information to change password.",
    oldPassword: "Old password",
    enterOldPassword: "Enter old password",
    newPassword: "New password",
    enterNewPassword: "Enter new password",
    confirmNewPassword: "Confirm new password",
    enterConfirmNewPassword: "Enter confirm new password",
    businessAccountChildAdd: "Business Account Child Add",
    originalQuotaByMonth: "Original Quota By Month",
    enterOriginalQuotaByMonth: "Enter original Quota by Month",
    cancel: "Cancel",
    confirmDelete: "Are you sure, you want to delete?",
    no: "No",
    businessAccountChildEdit: "Business Account Child Edit",
    edit: "Edit",
    update: "Update",
    uploadFiles: "Upload Files",
    dragAndDropFile: "Drag & drop, or browse your PDFs file",
    fromUrl: "From URL",
    listPDFFile: "List PDF File",
    fileName: "File Name",
    uploadedAt: "Uploaded At",
    lastModified: "Last Modified",
    fileSize: "File Size",
    showing: "Showing",
    to: "to",
    entries: "entries",
    logout: "Logout",
    upload: "Upload",
    chat: "Chat",
    validFileUrlError: "URL must start with https:// or http://",
    uploadFileUrlError: "Upload error. Could not read PDF.",
    welcome: "Welcome to CourseFusion",
  },
  vi: {
    welcome: "Chào mừng bạn đến với CourseFusion",
    profile: "Hồ sơ cá nhân",
    yourPhoto: "Ảnh của bạn",
    uploadPhoto: "Tải ảnh lên",
    name: "Tên",
    enterName: "Nhập tên",
    email: "Email",
    enterEmail: "Nhập địa chỉ email",
    password: "Mật khẩu",
    enterPassword: "Nhập mật khẩu",
    changePassword: "Đổi mật khẩu",
    updateProfile: "Cập nhật hồ sơ",
    listChildAccount: "Danh sách tài khoản con",
    show: "Hiển thị",
    rows: "dòng",
    add: "Thêm",
    delete: "Xóa",
    status: "Trạng thái",
    originalQuota: "Hạn ngạch gốc",
    remainQuota: "Hạn ngạch còn lại",
    action: "Hành động",
    company: "Tên công ty",
    enterCompany: "Nhập tên công ty",
    address: "Địa chỉ",
    enterAddress: "Nhập địa chỉ",
    currentTotalQuota: "Tổng hạn ngạch hiện tại",
    currentPlan: "Gói hiện tại",
    changePlan: "Thay đổi gói",
    buyMoreQuota: "Mua thêm hạn ngạch",
    businessOne: "Doanh nghiệp 1",
    token: "Mã thông báo",
    active: "Hoạt động",
    deactive: "Không hoạt động",
    pleaseEnterYourPassword: "Vui lòng nhập thông tin để đổi mật khẩu",
    oldPassword: "Mật khẩu hiện tại",
    enterOldPassword: "Nhập mật khẩu hiện tại",
    newPassword: "Mật khẩu mới",
    enterNewPassword: "Nhập mật khẩu mới",
    confirmNewPassword: "Xác nhận mật khẩu mới",
    enterConfirmNewPassword: "Nhập lại mật khẩu mới",
    change: "Thay đổi",
    businessAccountChildAdd: "Thêm tài khoản con vào tài khoản doanh nghiệp",
    originalQuotaByMonth: "Hạn ngạch gốc hàng tháng",
    enterOriginalQuotaByMonth: "Nhập số tín dụng ban đầu hàng tháng",
    cancel: "Hủy",
    confirmDelete: "Bạn có chắc chắn muốn xóa không?",
    no: "Không",
    businessAccountChildEdit: "Thêm tài khoản con",
    edit: "Chỉnh sửa",
    update: "Cập nhật",
    uploadFiles: "Tải tệp lên",
    dragAndDropFile: "Kéo và thả tệp PDF hoặc tải lên",
    fromUrl: "Tải từ URL",
    listPDFFile: "Danh sách tệp PDF",
    fileName: "Tên tệp",
    uploadedAt: "Ngày và giờ tải lên",
    lastModified: "Sửa đổi lần cuối",
    fileSize: "Kích thước tệp",
    showing: "Hiển thị",
    entries: "bản ghi",
    chatScreen: "Màn hình trò chuyện",
    logout: "Đăng xuất",
    login: "Đăng nhập",
    upload: "Tải lên PDF",
    chat: "Trò chuyện",
    validFileUrlError: 'URL phải bắt đầu bằng "https://" hoặc "http://"',
    uploadFileError: "Đã xảy ra lỗi khi tải lên, không thể lấy tệp PDF",
    noData: "Không có dữ liệu để hiển thị.",
    uploadFileSuccess: "Tải lên tệp thành công",
    deleteFileSuccess: "Xoá tệp thành công",
    monthlyPlan: "Gói hàng tháng",
    annualPlan: "Gói hàng năm",
    FAQ: {
      QA_1: "Có thể. Bạn có thể thêm tài khoản không giới hạn vào tài khoản với giá 7,500 Yên/người/tháng. Chúng tôi cũng cung cấp giảm giá số lượng, vui lòng liên hệ qua email support@octabio.com để biết thêm chi tiết.",
      QA_2: "Không. Liên quan đến việc học AI, điều này khác biệt so với Anika thông thường được công khai. Theo quy định của OpenAI về thông tin cá nhân, trong API thương mại bên ngoài được sử dụng cho dịch vụ này, các câu hỏi được cung cấp sẽ không được sử dụng để huấn luyện AI của OpenAI. Ngoài ra, các tệp PDF tải lên sẽ được lưu trữ trên một nền tảng đám mây được bảo vệ bởi mức độ bảo mật hàng đầu của ngành. Vì vậy, bạn có thể yên tâm về mặt bảo mật. Nếu bạn có bất kỳ câu hỏi nào về an ninh, vui lòng liên hệ qua email support@octabio.com để biết thêm chi tiết.",
      QA_3: "Thực tế hầu hết các trường hợp, câu trả lời chính xác phản ánh nội dung của tệp PDF gốc. Tuy nhiên, do tính chất của trí tuệ nhân tạo sinh ra, không phải lúc nào câu trả lời cũng chính xác tuyệt đối, phụ thuộc vào nội dung của câu hỏi. Vì lý do này, Anika cũng sẽ bao gồm liên kết đến tệp PDF gốc như một phần của câu trả lời. Vui lòng luôn kiểm tra nội dung tệp PDF gốc đối với thông tin quan trọng.",
      QA_4: "Hợp đồng Anika được gia hạn hàng tháng. Vì vậy, bạn có thể sử dụng dịch vụ trong một tháng và sau đó hủy đăng ký nếu muốn.",
      QA_5: "Rất tiếc, hiện tại chỉ hỗ trợ tải lên tệp PDF. Có kế hoạch để trong các phiên bản cập nhật tới, Anika sẽ hỗ trợ đọc các tệp CSV và các định dạng khác.",
    },
    screenChat: {
      credit_usage: {
        text_1: "Lượng sử dụng tín dụng (Số tín dụng còn lại ",
        text_2: ")",
      },
      management: "Quản lý",
      account: "Tài khoản chính",
      regular_account: "Tài khoản thường",
      remaining_credits: "Tín dụng còn lại",
      reset_chat: "Đặt lại trò chuyện",
      talkPDF: "Trò chuyện với PDF!",
      note_empty:
        "Bắt đầu trò chuyện mới bằng cách nhấn vào tên người dùng ở phía trên bên phải sau đó chọn tải lên tệp PDF hoặc chọn từ lịch sử.",
      start_new_chat: "Bắt đầu trò chuyện mới",
      dtag_drop_pdf: "Kéo và thả tệp PDF",
      load_fromUrl: "Tải từ URL",
      history: "Lịch sử",
      no_conversation_yet:
        "Chưa có cuộc trò chuyện nào. Hãy tạo cuộc trò chuyện mới.",
      search_pdf_files: "Tìm tệp PDF",
      getURL: "Lấy URL",
      searchInternet: "Tìm kiếm tệp PDF trên Internet",
      baseChat: "Trò chuyện cơ bản",
      filePDFChat: "Trò chuyện tệp tin PDF",
      askQuestion: "Xin vui lòng đặt câu hỏi của bạn",
    },
    toast: {
      upload_completed: "Đã tải lên thành công.",
      occurred_upload: "Có lỗi phát sinh khi tải lên",
      occurred: "Đã xảy ra lỗi",
      pdf_cannot_read: "Đã xảy ra lỗi khi tải lên.\nKhông thể đọc file PDF.",
      image_cannot_read:
        "Định dạng file không hợp lệ. Chỉ cho phép các file JFIF, JPEG, JPG, PNG.",
      pdf_larger_than_5MB: "Vui lòng chọn file dưới 5MB.",
      pdf_less_than_10MB: "Vui lòng chọn file dưới 10MB.",
      pdf_less_than_50MB: "Vui lòng chọn file dưới 50MB.",
      pdf_less_than_100MB: "Vui lòng chọn file dưới 100MB.",
      fail_pdf_less_than_32MB:
        "Đã xảy ra lỗi khi tải lên.\nDung lượng file PDF vượt quá 32MB. Vui lòng tải lên file dưới 32MB.",
      fail_image_less_than_8MB:
        "Đã xảy ra lỗi khi tải lên.\nVui lòng chọn file dưới 8MB.",
      profile_updated: "Cập nhật hồ sơ thành công.",
      email_address_not_found: "Không tìm thấy địa chỉ email.",
      no_plans_found: "Không tìm thấy kế hoạch nào.",
      payment_complete: "Thanh toán thành công.",
    },
    screenProfile: {
      original_credit: "Số tín dụng ban đầu",
      remaining_credits: "Số tín dụng còn lại",
      no_data: "Không có dữ liệu để hiển thị.",
      name_required: "Hãy nhập tên",
      company_name_required: "Tên công ty là một trường bắt buộc",
      adddress_required: "Địa chỉ là một trường bắt buộc",
    },
    screenPayment: {
      payment_goods: "Thanh toán cho hàng hóa",
      enter_card: "Vui lòng nhập thông tin thẻ để tiến hành thanh toán.",
      octabio: "© 2023. dattq0304. Đã được bảo lưu mọi quyền.",
    },
    go_to_login: "Tiếp tục",
    processing_file: "Đang xử lý file...",
    keep: "Lưu lại",
    freeTrial: "Dùng thử miễn phí",
    sevenDaysFree: "7 ngày miễn phí",
    singleUser: "(Người dùng đơn)",
    maximumPDFFileSizeTrial: "Dung lượng file PDF tối đa: 5MB/file",
    maximumUploadAndQuestionsTrial: "Tải lên 1 lần/ngày, hỏi 5 câu/ngày",
    startWithASevenDayFreeTrial: "Bắt đầu với gói dùng thử miễn phí 7 ngày",
    noCreditCardRequired: "Không cần thẻ tín dụng.",
    saveInfoLogin: "Lưu thông tin đăng nhập",
    validatedPassword8to32:
      "Mật khẩu của bạn phải từ 8 đến 32 kí tự, bao gồm cả chữ và số.",
    forgotPassword: "Quên mật khẩu?",
    resetPassword: "Thay đổi mật khẩu",
    requiredCurrentPassword: "Hãy nhập mật khẩu hiện tại",
    requiredNewPassword: "Hãy nhập mật khẩu mới",
    doNotMatch: "Mật khẩu mới không khớp. Hãy nhập lại mật khẩu mới tại đây.",
    noteResetPassword:
      "Khi bạn nhập địa chỉ email đã xác thực tài khoản người dùng \nsẽ có một liên kết để đặt lại mật khẩu gửi đến email đó.",
    backLogin: "Quay lại đăng nhập",
    requiredEmail: "Hãy nhập email",
    requiredPassword: "Hãy nhập mật khẩu",
    matchesPassword: "Trùng với mật khẩu hiện tại",
    invalidEmail: "Địa chỉ email không hợp lệ",
    maximumCharacter255: "Số ký tự nhập vào tối đa là 255 ký tự",
    editAccount: "Chỉnh sửa tài khoản",
    creditMonthly: "Số tín dụng ban đầu hàng tháng",
    sureLogout: "Đăng xuất khỏi tài khoản của bạn?",
    uploadedAndMerged: "Có thể tải lên và hợp nhất các tệp tin",
    myFile: "Tệp tin của tôi",
    shareMe: "Đã chia sẻ với tôi",
    share: "Chia sẻ",
    uploadMorePdf:
      "Nếu tải lên nhiều tệp PDF, hệ thống sẽ tự động hợp nhất tất cả",
    valid: "Hoạt động",
    invalid: "Tắt hoạt động",
    table: {
      name: "Tên tệp",
      date: "Ngày và giờ tải lên",
      size: "Kích thước tệp",
      access: "Quyền truy cập",
    },
    deleteFile: "Các tập tin và lịch sử trò chuyện cũng sẽ bị xóa.",
    introduce: {
      title:
        "Trí tuệ nhân tạo AI sẽ giúp bạn trả lời bất cứ điều gì về tài liệu nội bộ của công ty.",
      content:
        "Hỗ trợ đa ngôn ngữ cho các tài liệu PDF như hướng dẫn sử dụng, hợp đồng, tài liệu hỗ trợ và kế hoạch kinh doanh,...\nAnika là một trí tuệ nhân tạo có khả năng tạo ra và trả lời nội dung của tài liệu trong quá trình trò chuyện và bạn cũng có thể tự tải lên tài liệu của mình.",
    },
    contentResetPassword:
      "Chúng tôi đã gửi một liên kết để đặt lại mật khẩu, vui lòng kiểm tra email đã đăng ký. \nTrong vòng vài phút nếu bạn không nhận được liên kết ở hộp thư đến thì vui lòng kiểm tra thư mục rác.",
    free: "Dùng thử miễn phí",
    pdfTalk: "Anika là gì?",
    popular: "Câu hỏi phổ biến",
    creditsPerMonth: "Hãy nhập số tín dụng ban đầu hàng tháng từ 1 trở lên",
    shareSetting: "Cài đặt chia sẻ",
    addPeople: "Thêm người truy cập",
    deleteAll: "Xóa tất cả",
    onlyChat: "Có thể chat",
    editChatShare: "Có thể chat, chỉnh sửa, chia sẻ",
    viewOnly: "Chỉ nhìn thấy tên tệp",
    save: "Lưu",
    abolition: "Huỷ bỏ",
    notResult: "Không có kết quả",
    requiredOriginal: "Hãy nhập số tín dụng ban đầu hàng tháng",
    credit999999: "Hãy nhập số tín dụng ban đầu hàng tháng dưới 999999.",
    deleteFail: "Xóa tệp thất bại",
    enterNameAccess: "Nhập tên người truy cập",
    peopleAcess: "Người có quyền truy cập",
    notPeopleAcess: "Không có người truy cập nào",
    offShare: "Tắt chế độ chia sẻ",
    offAuthorShare: "Đã tắt quyền chia sẻ",
    finished: "Đã hoàn thành",
    revokePermission: "Thu hồi quyền",
    resetChat: "Đặt lại trò chuyện",
    i_dont_know: {
      text_1: "Xin lỗi, tôi không biết.",
      text_2: "Xin lỗi, tôi không biết",
      text_3: "Tôi không biết.",
      text_4: "Tôi không biết",
    },
  },
};

export default language;
